-- 017 down: drop the S2 orchestration progress table.
--
-- Wholly derived operational bookkeeping -- nothing here is evidence of a
-- human act (unlike filing_verifications), so dropping it loses nothing
-- that cannot be regenerated by re-running the affected batch_id.

DROP INDEX IF EXISTS idx_orchestration_progress_status;
DROP TABLE IF EXISTS orchestration_progress;
